option(FFT_FFTW "Use FFTW FFT" OFF)
option(FFT_PFFFT "Use PFFFT FFT" OFF)
option(FFT_VDSP "Use vDSP FFT" OFF)
option(FFT_MKL "Use MKL FFT" ON)

if (FFT_MKL)
    set(FFT_NAME "FFT_MKL")
    set(ENV{MKL_ROOT} /opt/intel/oneapi/mkl/latest)
    set(MKL_ARCH intel64)
    set(MKL_LINK static)
    set(MKL_THREADING sequential)
    set(MKL_INTERFACE_FULL intel_lp64)
    find_package(MKL CONFIG REQUIRED)
    set(FFT_INCLUDE_DIR $<TARGET_PROPERTY:MKL::MKL,INTERFACE_INCLUDE_DIRECTORIES>)
    set(FFT_LINK_CMD $<LINK_ONLY:MKL::MKL>)
elseif (FFT_PFFFT)
    set(FFT_NAME "FFT_PFFFT")
    set(FFT_INCLUDE_DIR /usr/local/include)
    set(FFT_LINK_CMD /usr/local/lib/libpffft.a)
elseif (FFT_VDSP)
    set(FFT_NAME "FFT_VDSP")
    set(FFT_INCLUDE_DIR "")
    set(FFT_LINK_CMD "-framework Accelerate")
elseif (FFT_FFTW)
    set(FFT_NAME "FFT_FFTW")
    set(FFTW_ROOT /opt/homebrew/Cellar/fftw/latest)
    set(FFT_INCLUDE_DIR ${FFTW_ROOT}/include)
    set(FFT_LINK_CMD ${FFTW_ROOT}/lib/libfftw3.a)
endif()

message(STATUS "FFT Selected: " ${FFT_NAME})