# FFT backend selection. Per-platform defaults; override with -DFFT_<NAME>=ON
# (the first enabled backend in the order MKL, PFFFT, vDSP, FFTW wins).
if (WIN32)
    option(FFT_MKL "Use MKL FFT" ON)
elseif (APPLE)
    option(FFT_VDSP "Use vDSP FFT" ON)
else()
    option(FFT_FFTW "Use FFTW FFT" ON) # Linux et al. (note: FFTW is GPL)
endif()

option(FFT_FFTW "Use FFTW FFT" OFF)
option(FFT_PFFFT "Use PFFFT FFT" OFF)
option(FFT_VDSP "Use vDSP FFT" OFF)
option(FFT_MKL "Use MKL FFT" OFF)

if (FFT_MKL)
    set(FFT_NAME "FFT_MKL")
    set(ENV{MKL_ROOT} /opt/intel/oneapi/mkl/latest)
    set(MKL_ARCH intel64)
    set(MKL_LINK static)
    set(MKL_THREADING sequential)
    set(MKL_INTERFACE_FULL intel_lp64)
    find_package(MKL CONFIG REQUIRED)
    set(FFT_INCLUDE_DIR $<TARGET_PROPERTY:MKL::MKL,INTERFACE_INCLUDE_DIRECTORIES>)
    set(FFT_LINK_CMD $<LINK_ONLY:MKL::MKL>)
elseif (FFT_PFFFT)
    set(FFT_NAME "FFT_PFFFT")
    set(FFT_INCLUDE_DIR /usr/local/include)
    set(FFT_LINK_CMD /usr/local/lib/libpffft.a)
elseif (FFT_VDSP)
    set(FFT_NAME "FFT_VDSP")
    set(FFT_INCLUDE_DIR "")
    set(FFT_LINK_CMD "-framework Accelerate")
elseif (FFT_FFTW)
    set(FFT_NAME "FFT_FFTW")
    find_path(FFTW_INCLUDE_DIR fftw3.h
        HINTS /opt/homebrew/include /usr/local/include /usr/include)
    find_library(FFTW_LIBRARY fftw3
        HINTS /opt/homebrew/lib /usr/local/lib)
    if (NOT FFTW_INCLUDE_DIR OR NOT FFTW_LIBRARY)
        message(FATAL_ERROR "FFTW not found — install it first "
            "(apt install libfftw3-dev / brew install fftw)")
    endif()
    set(FFT_INCLUDE_DIR ${FFTW_INCLUDE_DIR})
    set(FFT_LINK_CMD ${FFTW_LIBRARY})
else()
    message(FATAL_ERROR "No FFT backend selected (enable one of FFT_MKL, "
        "FFT_PFFFT, FFT_VDSP, FFT_FFTW)")
endif()

message(STATUS "FFT Selected: " ${FFT_NAME})
